name: Push tag

on:
  create:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-[a-z].*"
jobs:
  on_push_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "show nightly tag"
        run: |
          git tags
